// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Bns-3SQuUvzqy42HBtGKPDU99qoyqnA',
    appId: '1:833185535926:web:b5cf72950e085d1b6a5317',
    messagingSenderId: '833185535926',
    projectId: 'sobieh-coffee-99fbd',
    authDomain: 'sobieh-coffee-99fbd.firebaseapp.com',
    storageBucket: 'sobieh-coffee-99fbd.firebasestorage.app',
    measurementId: 'G-EHBYHCY7ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlZ7Woz8rC8SOmtdgEDcM7i4cK0OB6_vg',
    appId: '1:833185535926:android:64e2ccd33b7610bb6a5317',
    messagingSenderId: '833185535926',
    projectId: 'sobieh-coffee-99fbd',
    storageBucket: 'sobieh-coffee-99fbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYVzAlSei1rmkwaUPSPVRnJMp4Osx7rno',
    appId: '1:833185535926:ios:d688d4e72dc1bcbe6a5317',
    messagingSenderId: '833185535926',
    projectId: 'sobieh-coffee-99fbd',
    storageBucket: 'sobieh-coffee-99fbd.firebasestorage.app',
    iosBundleId: 'com.sobieh.coffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYVzAlSei1rmkwaUPSPVRnJMp4Osx7rno',
    appId: '1:833185535926:ios:24341b9ac31b5f976a5317',
    messagingSenderId: '833185535926',
    projectId: 'sobieh-coffee-99fbd',
    storageBucket: 'sobieh-coffee-99fbd.firebasestorage.app',
    iosBundleId: 'com.sobieh.coffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Bns-3SQuUvzqy42HBtGKPDU99qoyqnA',
    appId: '1:833185535926:web:986aa5f685c2c34b6a5317',
    messagingSenderId: '833185535926',
    projectId: 'sobieh-coffee-99fbd',
    authDomain: 'sobieh-coffee-99fbd.firebaseapp.com',
    storageBucket: 'sobieh-coffee-99fbd.firebasestorage.app',
    measurementId: 'G-8CW2RFB65B',
  );
}
